import mongoose from 'mongoose';
import Doctor from '../models/Doctor';
import { connectToDatabase } from '../lib/db/connection';

// Define sample data
const doctors = [
  {
    name: 'Dr. Lakshmi Sindhura Kakani',
    title: 'General Physician/ Internal Medicine Specialist',
    experience: 10,
    qualifications: ['MBBS', 'MD (General medicine)'],
    location: {
      city: 'Visakhapatnam',
      state: 'Andhra Pradesh',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    fees: 499,
    isAvailable: true,
    availableIn: 0,
    specialties: ['General Physician', 'Internal Medicine'],
    gender: 'female',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Md Yusuf Shareef',
    title: 'General Practitioner',
    experience: 8,
    qualifications: ['MBBS'],
    location: {
      city: 'Hyderabad',
      state: 'Telangana',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    rating: 83,
    totalReviews: 50,
    fees: 399,
    cashback: 60,
    isAvailable: true,
    availableIn: 0,
    specialties: ['General Practitioner', 'Family Medicine'],
    gender: 'male',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Rohinipriyanka Reddy',
    title: 'General Practitioner',
    experience: 9,
    qualifications: ['MBBS'],
    location: {
      city: 'Hyderabad',
      state: 'Telangana',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    rating: 85,
    totalReviews: 100,
    fees: 479,
    cashback: 72,
    isAvailable: true,
    availableIn: 2,
    specialties: ['General Practitioner'],
    gender: 'female',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Summaiya Banu',
    title: 'General Practitioner',
    experience: 8,
    qualifications: ['MBBS'],
    location: {
      city: 'Hyderabad',
      state: 'Telangana',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    rating: 84,
    totalReviews: 100,
    fees: 499,
    cashback: 75,
    isAvailable: true,
    availableIn: 3,
    specialties: ['General Practitioner'],
    gender: 'female',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Jawwad Mohammed Kaleem',
    title: 'General Practitioner',
    experience: 4,
    qualifications: ['MBBS'],
    location: {
      city: 'Hyderabad',
      state: 'Telangana',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    fees: 379,
    cashback: 57,
    isAvailable: true,
    availableIn: 6,
    specialties: ['General Practitioner'],
    gender: 'male',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Shaik Abdul Kalam',
    title: 'General Practitioner',
    experience: 3,
    qualifications: ['MD (Physician)'],
    location: {
      city: 'Visakhapatnam',
      state: 'Andhra Pradesh',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    rating: 94,
    totalReviews: 50,
    fees: 399,
    cashback: 60,
    isAvailable: true,
    availableIn: 10,
    specialties: ['General Practitioner'],
    gender: 'male',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Chandra Sekhar P',
    title: 'General Practitioner',
    experience: 5,
    qualifications: ['MBBS'],
    location: {
      city: 'Bangalore',
      state: 'Karnataka',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    fees: 399,
    cashback: 60,
    isAvailable: true,
    availableIn: 11,
    specialties: ['General Practitioner'],
    gender: 'male',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Yaazhisai G K',
    title: 'General Practitioner',
    experience: 5,
    qualifications: ['MBBS'],
    location: {
      city: 'Chennai',
      state: 'Tamilnadu',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    fees: 399,
    cashback: 60,
    isAvailable: true,
    availableIn: 12,
    specialties: ['General Practitioner'],
    gender: 'female',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. M L Ezhilarasan',
    title: 'General Practitioner',
    experience: 6,
    qualifications: ['MBBS'],
    location: {
      city: 'Visakhapatnam',
      state: 'Andhra Pradesh',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    fees: 399,
    cashback: 60,
    isAvailable: true,
    availableIn: 12,
    specialties: ['General Practitioner'],
    gender: 'male',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Shesham Srinidhi',
    title: 'General Practitioner',
    experience: 5,
    qualifications: ['MD(physician)'],
    location: {
      city: 'Hyderabad',
      state: 'Telangana',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    rating: 91,
    totalReviews: 75,
    fees: 399,
    cashback: 60,
    isAvailable: true,
    availableIn: 13,
    specialties: ['General Practitioner'],
    gender: 'female',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Syed Ismail Ali',
    title: 'General Practitioner',
    experience: 7,
    qualifications: ['MBBS'],
    location: {
      city: 'Hyderabad',
      state: 'Telangana',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    fees: 399,
    cashback: 60,
    isAvailable: true,
    availableIn: 13,
    specialties: ['General Practitioner'],
    gender: 'male',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Immanuel Raj',
    title: 'General Practitioner',
    experience: 8,
    qualifications: ['MBBS', 'MBA (HHSM)'],
    location: {
      city: 'Hyderabad',
      state: 'Telangana',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    fees: 450,
    cashback: 68,
    isAvailable: false,
    nextAvailableTime: new Date('2025-04-28T14:30:00Z'),
    specialties: ['General Practitioner'],
    gender: 'male',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. D Bhanu Prakash',
    title: 'General Practitioner',
    experience: 10,
    qualifications: ['MBBS', 'AFIH', 'Advanced certificate in critical care medicine', 'Fellowship in critical care medicine'],
    location: {
      city: 'Hyderabad',
      state: 'Telangana',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    fees: 489,
    cashback: 73,
    isAvailable: false,
    nextAvailableTime: new Date('2025-04-28T14:44:00Z'),
    specialties: ['General Practitioner', 'Critical Care'],
    gender: 'male',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Kanika Bansal',
    title: 'General Physician/ Internal Medicine Specialist',
    experience: 6,
    qualifications: ['MBBS', 'DNB (General Medicine)'],
    location: {
      city: 'New Delhi',
      state: 'Delhi',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    rating: 82,
    totalReviews: 250,
    fees: 489,
    cashback: 73,
    isAvailable: false,
    nextAvailableTime: new Date('2025-04-28T16:00:00Z'),
    specialties: ['General Physician', 'Internal Medicine'],
    gender: 'female',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Suraja Nutulapati',
    title: 'General Physician/ Internal Medicine Specialist',
    experience: 10,
    qualifications: ['MBBS', 'MD (Internal Medicine)'],
    location: {
      city: 'Hyderabad',
      state: 'Telangana',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    rating: 90,
    totalReviews: 800,
    fees: 499,
    cashback: 75,
    isAvailable: false,
    nextAvailableTime: new Date('2025-04-29T01:30:00Z'),
    specialties: ['General Physician', 'Internal Medicine'],
    gender: 'female',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Ananya Sharma',
    title: 'General Physician/ Internal Medicine Specialist',
    experience: 12,
    qualifications: ['MBBS', 'MD (Internal Medicine)', 'DM (Cardiology)'],
    location: {
      city: 'Mumbai',
      state: 'Maharashtra',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    rating: 95,
    totalReviews: 1200,
    fees: 799,
    cashback: 120,
    isAvailable: true,
    specialties: ['General Physician', 'Internal Medicine', 'Cardiology'],
    gender: 'female',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Rajesh Kumar',
    title: 'General Physician/ Internal Medicine Specialist',
    experience: 15,
    qualifications: ['MBBS', 'MD (Internal Medicine)', 'DNB (General Medicine)'],
    location: {
      city: 'Bangalore',
      state: 'Karnataka',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    rating: 94,
    totalReviews: 950,
    fees: 699,
    cashback: 105,
    isAvailable: false,
    nextAvailableTime: new Date('2025-04-29T10:00:00Z'),
    specialties: ['General Physician', 'Internal Medicine', 'Diabetes Care'],
    gender: 'male',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Priya Patel',
    title: 'General Physician/ Internal Medicine Specialist',
    experience: 8,
    qualifications: ['MBBS', 'MD (Internal Medicine)'],
    location: {
      city: 'Ahmedabad',
      state: 'Gujarat',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    rating: 92,
    totalReviews: 600,
    fees: 599,
    cashback: 90,
    isAvailable: true,
    specialties: ['General Physician', 'Internal Medicine', 'Women\'s Health'],
    gender: 'female',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Vikram Singh',
    title: 'General Physician/ Internal Medicine Specialist',
    experience: 20,
    qualifications: ['MBBS', 'MD (Internal Medicine)', 'DM (Nephrology)'],
    location: {
      city: 'Delhi',
      state: 'Delhi',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    rating: 96,
    totalReviews: 1500,
    fees: 899,
    cashback: 135,
    isAvailable: false,
    nextAvailableTime: new Date('2025-04-29T15:30:00Z'),
    specialties: ['General Physician', 'Internal Medicine', 'Nephrology'],
    gender: 'male',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Meera Nair',
    title: 'General Physician/ Internal Medicine Specialist',
    experience: 7,
    qualifications: ['MBBS', 'MD (Internal Medicine)'],
    location: {
      city: 'Kochi',
      state: 'Kerala',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    rating: 91,
    totalReviews: 450,
    fees: 549,
    cashback: 82,
    isAvailable: true,
    specialties: ['General Physician', 'Internal Medicine', 'Geriatric Care'],
    gender: 'female',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Arjun Reddy',
    title: 'General Physician/ Internal Medicine Specialist',
    experience: 11,
    qualifications: ['MBBS', 'MD (Internal Medicine)', 'DM (Pulmonary Medicine)'],
    location: {
      city: 'Chennai',
      state: 'Tamil Nadu',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    rating: 93,
    totalReviews: 800,
    fees: 649,
    cashback: 97,
    isAvailable: false,
    nextAvailableTime: new Date('2025-04-29T12:00:00Z'),
    specialties: ['General Physician', 'Internal Medicine', 'Pulmonary Medicine'],
    gender: 'male',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Neha Gupta',
    title: 'General Physician/ Internal Medicine Specialist',
    experience: 9,
    qualifications: ['MBBS', 'MD (Internal Medicine)', 'DNB (General Medicine)'],
    location: {
      city: 'Pune',
      state: 'Maharashtra',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    rating: 92,
    totalReviews: 700,
    fees: 599,
    cashback: 90,
    isAvailable: true,
    specialties: ['General Physician', 'Internal Medicine', 'Preventive Medicine'],
    gender: 'female',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Sanjay Mehta',
    title: 'General Physician/ Internal Medicine Specialist',
    experience: 18,
    qualifications: ['MBBS', 'MD (Internal Medicine)', 'DM (Gastroenterology)'],
    location: {
      city: 'Kolkata',
      state: 'West Bengal',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    rating: 95,
    totalReviews: 1100,
    fees: 749,
    cashback: 112,
    isAvailable: false,
    nextAvailableTime: new Date('2025-04-29T14:00:00Z'),
    specialties: ['General Physician', 'Internal Medicine', 'Gastroenterology'],
    gender: 'male',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Aisha Khan',
    title: 'General Physician/ Internal Medicine Specialist',
    experience: 6,
    qualifications: ['MBBS', 'MD (Internal Medicine)'],
    location: {
      city: 'Lucknow',
      state: 'Uttar Pradesh',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    rating: 90,
    totalReviews: 400,
    fees: 499,
    cashback: 75,
    isAvailable: true,
    specialties: ['General Physician', 'Internal Medicine', 'Pediatric Care'],
    gender: 'female',
    imageUrl: '/placeholder-doctor.jpg',
  },
  {
    name: 'Dr. Ravi Verma',
    title: 'General Physician/ Internal Medicine Specialist',
    experience: 14,
    qualifications: ['MBBS', 'MD (Internal Medicine)', 'DM (Neurology)'],
    location: {
      city: 'Jaipur',
      state: 'Rajasthan',
    },
    clinic: 'Apollo 24|7 Virtual Clinic',
    rating: 94,
    totalReviews: 900,
    fees: 699,
    cashback: 105,
    isAvailable: false,
    nextAvailableTime: new Date('2025-04-29T16:30:00Z'),
    specialties: ['General Physician', 'Internal Medicine', 'Neurology'],
    gender: 'male',
    imageUrl: '/placeholder-doctor.jpg',
  }
];

// Seed database function
async function seedDatabase() {
  try {
    // Connect to the database
    await connectToDatabase();
    
    // Clear existing data
    await Doctor.deleteMany({});
    console.log('Cleared existing data');
    
    // Insert new data
    await Doctor.insertMany(doctors);
    console.log(`Successfully seeded ${doctors.length} doctors to the database`);
    
    // Close the connection
    await mongoose.disconnect();
    console.log('Database connection closed');
  } catch (error) {
    console.error('Error seeding database:', error);
    process.exit(1);
  }
}

// Run the seed function
seedDatabase(); 